// Copyright (c) 2012-2018, The CryptoNote developers, The Bytecoin developers.
// Licensed under the GNU Lesser General Public License. See LICENSE for details.

#include "test_zk.hpp"
#include <array>
#include <iostream>
#include <string>
#include "Core/zk/Halo2ProofSystem.hpp"
#include "common/Invariant.hpp"
#include "onyx_zk.h"

using namespace cn;
using namespace cn::zk;

static std::string to_hex(const uint8_t *b, size_t n) {
	static const char *d = "0123456789abcdef";
	std::string s;
	s.reserve(n * 2);
	for (size_t i = 0; i < n; ++i) {
		s.push_back(d[b[i] >> 4]);
		s.push_back(d[b[i] & 0xf]);
	}
	return s;
}

static BinaryArray from_hex(const std::string &hex) {
	invariant(hex.size() % 2 == 0, "invalid hex fixture length");
	BinaryArray bytes;
	bytes.reserve(hex.size() / 2);
	const auto nibble = [](char ch) -> uint8_t {
		if (ch >= '0' && ch <= '9')
			return static_cast<uint8_t>(ch - '0');
		if (ch >= 'a' && ch <= 'f')
			return static_cast<uint8_t>(ch - 'a' + 10);
		invariant(false, "invalid hex fixture character");
		return 0;
	};
	for (size_t i = 0; i != hex.size(); i += 2)
		bytes.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
	return bytes;
}

void test_zk() {
	Halo2ProofSystem ps;
	std::cout << "  backend: " << ps.backend_id() << std::endl;
	invariant(Halo2ProofSystem::abi_version() == ONYX_ZK_ABI_VERSION, "unexpected Onyx C ABI version");
	std::cout << "  [zk] C ABI v" << Halo2ProofSystem::abi_version() << " ok" << std::endl;

	// 1. Poseidon known-answer vector (must match vendor/onyx-zk/test_vectors.md, generated by the
	//    Rust reference). Catches any drift in the vendored primitive or the FFI marshalling.
	{
		uint8_t in[64];
		std::fill(std::begin(in), std::end(in), uint8_t(7));
		uint8_t out[32] = {};
		invariant(Halo2ProofSystem::poseidon_hash2(in, out), "poseidon_hash2 failed");
		const std::string got = to_hex(out, 32);
		const std::string want = "254e33e5ae446f78a45786a91a014e3da7d5423c5c6e38cc748ed0c98fde7f14";
		invariant(got == want, "Poseidon KAT mismatch: got " + got);
		std::cout << "  [zk] poseidon2 KAT ok" << std::endl;
	}

	// 2. Sinsemilla known-answer vector.
	{
		const BinaryArray in{'o', 'n', 'y', 'x'};
		uint8_t out[32] = {};
		invariant(Halo2ProofSystem::sinsemilla_hash(in, out), "sinsemilla_hash failed");
		const std::string got = to_hex(out, 32);
		const std::string want = "19b2738d4ee7132b21a2bed59918192ce7681e1da34d2a695fdfa47fed874e18";
		invariant(got == want, "Sinsemilla KAT mismatch: got " + got);
		std::cout << "  [zk] sinsemilla KAT ok" << std::endl;
	}

	// 3. Toy prove -> verify round trip across the FFI, through the IProofSystem interface.
	{
		BinaryArray proof, vk_bytes;
		std::array<uint8_t, 32> public_in{};
		invariant(Halo2ProofSystem::toy_prove(6, 7, &proof, &vk_bytes, &public_in), "toy_prove failed");

		VerifyingKey vk;
		vk.data = vk_bytes;
		ProofVerifyArgs ok_args;
		ok_args.proof          = proof;
		ok_args.public_inputs  = BinaryArray(public_in.begin(), public_in.end());
		invariant(ps.verify(vk, ok_args), "valid toy proof must verify");

		ProofVerifyArgs bad_args = ok_args;
		bad_args.public_inputs[0] ^= 1;  // tamper the public statement
		invariant(!ps.verify(vk, bad_args), "tampered public input must not verify");
		std::cout << "  [zk] toy prove->verify round trip ok" << std::endl;

		// 4. Batch verify returns one result per item, in order.
		std::vector<const VerifyingKey *> vks{&vk, &vk};
		std::vector<ProofVerifyArgs> items{ok_args, bad_args};
		const std::vector<bool> res = ps.verify_batch(vks, items);
		invariant(res.size() == 2 && res[0] && !res[1], "verify_batch returned wrong results");
		const std::vector<bool> missing_keys = ps.verify_batch({}, items);
		invariant(missing_keys.size() == 2 && !missing_keys[0] && !missing_keys[1],
		    "verify_batch accepted a key/item shape mismatch");
		const std::vector<const VerifyingKey *> null_keys{nullptr, &vk};
		const std::vector<bool> null_result = ps.verify_batch(null_keys, items);
		invariant(null_result.size() == 2 && !null_result[0] && !null_result[1],
		    "verify_batch accepted a null verifying key");
		std::cout << "  [zk] verify_batch ok" << std::endl;
	}

	// 5. Canonical authorized-envelope boundary fails closed on empty, malformed, and unsupported
	// circuit selections before any proof work.
	{
		invariant(!Halo2ProofSystem::verify_authorized_transfer(BinaryArray{}, 32, 20),
		    "empty authorized transfer must fail");
		const BinaryArray malformed{0x06, 0x00, 0xff};
		invariant(!Halo2ProofSystem::verify_authorized_transfer(malformed, 32, 20),
		    "malformed authorized transfer must fail");
		invariant(!Halo2ProofSystem::verify_authorized_transfer(malformed, 32, 21),
		    "unsupported circuit K must fail");
		BinaryArray next_snapshot;
		uint64_t fee = 0;
		std::array<uint8_t, 16> network{};
		invariant(!Halo2ProofSystem::verify_apply_transfer(BinaryArray{}, 100, malformed, 32, 20,
		              network, 1, &next_snapshot, &fee),
		    "malformed state transition must fail");
		invariant(next_snapshot.empty() && fee == 0, "failed state transition modified outputs");
		std::array<uint8_t, 32> seed{};
		std::array<uint8_t, 91> address{};
		invariant(Halo2ProofSystem::wallet_address(seed, network, 0, &address),
		    "Onyx wallet address derivation failed");
		std::array<uint8_t, 177> viewing_key{};
		invariant(Halo2ProofSystem::full_viewing_key(seed, network, &viewing_key),
		    "Onyx full viewing-key derivation failed");
		Halo2ProofSystem::WalletScanResult scan;
		invariant(!Halo2ProofSystem::wallet_scan(BinaryArray{}, seed, network, 0, 1, 20, malformed,
		              &next_snapshot, &scan),
		    "malformed wallet scan input must fail");
		invariant(!Halo2ProofSystem::wallet_scan_viewing(BinaryArray{},
		              BinaryArray(viewing_key.begin(), viewing_key.end()), 0, 1, 20, malformed, &next_snapshot, &scan),
		    "malformed viewing-wallet scan input must fail");
		std::cout << "  [zk] authorized-transfer boundary rejects malformed input" << std::endl;
	}

	// 6. A deterministic funded wallet crosses the production C ABI/C++ adapter to prove both an
	// approved-program deployment and a stateful NFT call. The Rust regression test pins the
	// fixture digest and witness primitive so format or cryptographic drift cannot silently stale it.
	{
		const BinaryArray wallet_snapshot = from_hex(
#include "standard_program_wallet_fixture.inc"
		);
		std::array<uint8_t, 32> seed{};
		seed.fill(44);
		BinaryArray deployment{0xff};
		std::array<uint8_t, 32> program_id{};
		program_id.fill(0xff);
		invariant(Halo2ProofSystem::wallet_create_standard_program_deployment(wallet_snapshot, seed,
		              1, 9, 10, 0, 20, 100000, 16, &deployment, &program_id),
		    "standard NFT deployment proving failed through C++ adapter");
		Halo2ProofSystem::VerifiedProgramDeployment verified_deployment;
		invariant(Halo2ProofSystem::verify_program_deployment(deployment, 32, 16, &verified_deployment),
		    "C++ adapter produced an invalid standard-program deployment");
		invariant(verified_deployment.program_id == program_id,
		    "deployment prover and verifier disagreed on program id");

		BinaryArray application{1, 1};
		application.resize(66, 0);
		application[2]  = 21;
		application[34] = 22;
		application.push_back(33);
		application.push_back(1);
		std::array<uint8_t, 32> prior_state{};
		const BinaryArray prior =
		    from_hex("dea354729d447a92315a7730a8ffa9c2621f025a2e73cf2c794b7923939f1a00");
		std::copy(prior.begin(), prior.end(), prior_state.begin());
		std::array<uint8_t, 32> next_state{};
		next_state[0] = 0x85;
		next_state[1] = 0x03;
		BinaryArray witness(32, 0);
		witness[0] = 34;
		BinaryArray transaction{0xff};
		invariant(Halo2ProofSystem::wallet_create_standard_program_call(wallet_snapshot, seed, program_id,
		              10, 10, 20, application, prior_state, next_state, witness, 16, &transaction),
		    "standard NFT call proving failed through C++ adapter");
		Halo2ProofSystem::VerifiedTransferDelta delta;
		std::vector<std::array<uint8_t, 32>> state_keys;
		invariant(Halo2ProofSystem::extract_authenticated_standard_program_delta(
		              transaction, &delta, &state_keys),
		    "C++ adapter produced an unauthenticated standard-program call");
		invariant(state_keys.size() == 1, "standard NFT call did not authenticate exactly one state key");

		BinaryArray stale_output{0xff};
		std::array<uint8_t, 32> stale_id{};
		stale_id.fill(0xff);
		invariant(!Halo2ProofSystem::wallet_create_standard_program_deployment(wallet_snapshot, seed,
		              0, 9, 10, 0, 20, 100000, 16, &stale_output, &stale_id),
		    "invalid standard-program kind was accepted");
		const bool deployment_outputs_cleared =
		    stale_output.empty() && stale_id == std::array<uint8_t, 32>{};
		invariant(deployment_outputs_cleared, "failed deployment proving left stale outputs");
		stale_output.assign(1, 0xff);
		invariant(!Halo2ProofSystem::wallet_create_standard_program_call(wallet_snapshot, seed, program_id,
		              10, 10, 20, BinaryArray{}, prior_state, next_state, witness, 16, &stale_output),
		    "empty standard-program application was accepted");
		invariant(stale_output.empty(), "failed standard-program call proving left stale output");
		std::cout << "  [zk] standard-program deployment and NFT call proving boundary ok" << std::endl;
	}

	// 7. Exercise the complete bridge adapter boundary: wallet proving, ownership-signature
	// insertion, proof verification, state application, supply accounting, and replay rejection.
	{
		std::array<uint8_t, 32> seed{};
		seed.fill(3);
		std::array<uint8_t, 16> network{};
		network.fill(4);
		std::array<uint8_t, 91> recipient{};
		invariant(Halo2ProofSystem::wallet_address(seed, network, 0, &recipient),
		    "bridge recipient derivation failed");
		std::array<uint8_t, 32> key_image{};
		key_image.fill(7);
		const BinaryArray memo{'b', 'r', 'i', 'd', 'g', 'e'};
		BinaryArray unsigned_bridge;
		std::array<uint8_t, 32> ownership_sighash{};
		invariant(Halo2ProofSystem::wallet_create_bridge(seed, recipient, 100, 5, 30, 42,
		              key_image, memo, 13, &unsigned_bridge, &ownership_sighash),
		    "bridge proving failed through C++ adapter");
		std::array<uint8_t, 64> ownership_signature{};
		ownership_signature.fill(9);
		BinaryArray bridge;
		invariant(Halo2ProofSystem::wallet_finalize_bridge(
		              unsigned_bridge, ownership_signature, &bridge),
		    "bridge finalization failed through C++ adapter");

		Halo2ProofSystem::VerifiedBridgeDelta verified;
		invariant(Halo2ProofSystem::verify_bridge(bridge, 13, &verified),
		    "wallet bridge proof did not verify through C++ adapter");
		invariant(verified.legacy_amount == 30 && verified.fee == 5 &&
		              verified.legacy_stack_index == 42 && verified.legacy_key_image == key_image &&
		              verified.ownership_sighash == ownership_sighash &&
		              verified.ownership_signature == ownership_signature,
		    "verified bridge fields changed across the C ABI");

		BinaryArray state;
		invariant(Halo2ProofSystem::verify_apply_bridge(
		              BinaryArray{}, 100, bridge, 13, network, 1, &state, &verified),
		    "valid bridge state application failed");
		Halo2ProofSystem::SupplyAudit audit;
		invariant(Halo2ProofSystem::state_supply_audit(state, &audit),
		    "bridge supply audit failed");
		invariant(audit.total_bridged == 30 && audit.total_fees == 5 &&
		              audit.circulating_supply == 25 && audit.commitment_count == 1,
		    "bridge supply audit violated value conservation");

		BinaryArray stale_state{0xff};
		verified.legacy_amount = 99;
		invariant(!Halo2ProofSystem::verify_apply_bridge(
		              state, 100, bridge, 13, network, 2, &stale_state, &verified),
		    "replayed bridge was accepted");
		invariant(stale_state.empty() && verified.legacy_amount == 0,
		    "rejected bridge application left stale outputs");
		BinaryArray stale_bridge{0xff};
		ownership_sighash.fill(0xff);
		invariant(!Halo2ProofSystem::wallet_create_bridge(seed, recipient, 100, 30, 30, 42,
		              key_image, memo, 13, &stale_bridge, &ownership_sighash),
		    "non-conserving bridge was accepted");
		const bool bridge_outputs_cleared =
		    stale_bridge.empty() && ownership_sighash == std::array<uint8_t, 32>{};
		invariant(bridge_outputs_cleared,
		    "rejected bridge proving left stale outputs");
		stale_bridge.assign(1, 0xff);
		invariant(!Halo2ProofSystem::wallet_finalize_bridge(
		              BinaryArray{}, ownership_signature, &stale_bridge),
		    "empty bridge finalization was accepted");
		invariant(stale_bridge.empty(), "rejected bridge finalization left stale output");
		stale_bridge.assign(1, 0xff);
		invariant(!Halo2ProofSystem::wallet_create_bridge(seed, recipient, 100, 5, 30, 42,
		              key_image, memo, 13, &stale_bridge, nullptr),
		    "bridge proving accepted a null sighash output");
		invariant(stale_bridge.empty(), "null bridge sighash output left stale envelope bytes");
		ownership_sighash.fill(0xff);
		invariant(!Halo2ProofSystem::wallet_create_bridge(seed, recipient, 100, 5, 30, 42,
		              key_image, memo, 13, nullptr, &ownership_sighash),
		    "bridge proving accepted a null envelope output");
		const bool null_envelope_sighash_cleared =
		    ownership_sighash == std::array<uint8_t, 32>{};
		invariant(null_envelope_sighash_cleared,
		    "null bridge envelope output left a stale sighash");
		verified.legacy_amount = 99;
		invariant(!Halo2ProofSystem::verify_apply_bridge(
		              state, 100, bridge, 13, network, 2, nullptr, &verified),
		    "bridge apply accepted a null snapshot output");
		invariant(verified.legacy_amount == 0,
		    "null bridge snapshot output left a stale verified delta");
		stale_state.assign(1, 0xff);
		invariant(!Halo2ProofSystem::verify_apply_bridge(
		              state, 100, bridge, 13, network, 2, &stale_state, nullptr),
		    "bridge apply accepted a null delta output");
		invariant(stale_state.empty(), "null bridge delta output left a stale snapshot");
		std::cout << "  [zk] bridge proving, replay defense, and supply accounting ok" << std::endl;
	}

	std::cout << "  test_zk: OK" << std::endl;
}
