// Copyright (c) 2012-2018, The CryptoNote developers, The Bytecoin developers.
// Licensed under the GNU Lesser General Public License. See LICENSE for details.

#include "test_zk.hpp"
#include <array>
#include <iostream>
#include <string>
#include "Core/zk/Halo2ProofSystem.hpp"
#include "common/Invariant.hpp"

using namespace cn;
using namespace cn::zk;

static std::string to_hex(const uint8_t *b, size_t n) {
	static const char *d = "0123456789abcdef";
	std::string s;
	s.reserve(n * 2);
	for (size_t i = 0; i < n; ++i) {
		s.push_back(d[b[i] >> 4]);
		s.push_back(d[b[i] & 0xf]);
	}
	return s;
}

void test_zk() {
	Halo2ProofSystem ps;
	std::cout << "  backend: " << ps.backend_id() << std::endl;

	// 1. Poseidon known-answer vector (must match vendor/onyx-zk/test_vectors.md, generated by the
	//    Rust reference). Catches any drift in the vendored primitive or the FFI marshalling.
	{
		uint8_t in[64];
		std::fill(std::begin(in), std::end(in), uint8_t(7));
		uint8_t out[32] = {};
		invariant(Halo2ProofSystem::poseidon_hash2(in, out), "poseidon_hash2 failed");
		const std::string got = to_hex(out, 32);
		const std::string want = "254e33e5ae446f78a45786a91a014e3da7d5423c5c6e38cc748ed0c98fde7f14";
		invariant(got == want, "Poseidon KAT mismatch: got " + got);
		std::cout << "  [zk] poseidon2 KAT ok" << std::endl;
	}

	// 2. Sinsemilla known-answer vector.
	{
		const BinaryArray in{'o', 'n', 'y', 'x'};
		uint8_t out[32] = {};
		invariant(Halo2ProofSystem::sinsemilla_hash(in, out), "sinsemilla_hash failed");
		const std::string got = to_hex(out, 32);
		const std::string want = "19b2738d4ee7132b21a2bed59918192ce7681e1da34d2a695fdfa47fed874e18";
		invariant(got == want, "Sinsemilla KAT mismatch: got " + got);
		std::cout << "  [zk] sinsemilla KAT ok" << std::endl;
	}

	// 3. Toy prove -> verify round trip across the FFI, through the IProofSystem interface.
	{
		BinaryArray proof, vk_bytes;
		std::array<uint8_t, 32> public_in{};
		invariant(Halo2ProofSystem::toy_prove(6, 7, &proof, &vk_bytes, &public_in), "toy_prove failed");

		VerifyingKey vk;
		vk.data = vk_bytes;
		ProofVerifyArgs ok_args;
		ok_args.proof          = proof;
		ok_args.public_inputs  = BinaryArray(public_in.begin(), public_in.end());
		invariant(ps.verify(vk, ok_args), "valid toy proof must verify");

		ProofVerifyArgs bad_args = ok_args;
		bad_args.public_inputs[0] ^= 1;  // tamper the public statement
		invariant(!ps.verify(vk, bad_args), "tampered public input must not verify");
		std::cout << "  [zk] toy prove->verify round trip ok" << std::endl;

		// 4. Batch verify returns one result per item, in order.
		std::vector<const VerifyingKey *> vks{&vk, &vk};
		std::vector<ProofVerifyArgs> items{ok_args, bad_args};
		const std::vector<bool> res = ps.verify_batch(vks, items);
		invariant(res.size() == 2 && res[0] && !res[1], "verify_batch returned wrong results");
		std::cout << "  [zk] verify_batch ok" << std::endl;
	}

	// 5. Canonical authorized-envelope boundary fails closed on empty, malformed, and unsupported
	// circuit selections before any proof work.
	{
		invariant(!Halo2ProofSystem::verify_authorized_transfer(BinaryArray{}, 32, 20),
		    "empty authorized transfer must fail");
		const BinaryArray malformed{0x06, 0x00, 0xff};
		invariant(!Halo2ProofSystem::verify_authorized_transfer(malformed, 32, 20),
		    "malformed authorized transfer must fail");
		invariant(!Halo2ProofSystem::verify_authorized_transfer(malformed, 32, 21),
		    "unsupported circuit K must fail");
		BinaryArray next_snapshot;
		uint64_t fee = 0;
		std::array<uint8_t, 16> network{};
		invariant(!Halo2ProofSystem::verify_apply_transfer(BinaryArray{}, 100, malformed, 32, 20,
		              network, 1, &next_snapshot, &fee),
		    "malformed state transition must fail");
		invariant(next_snapshot.empty() && fee == 0, "failed state transition modified outputs");
		std::cout << "  [zk] authorized-transfer boundary rejects malformed input" << std::endl;
	}

	std::cout << "  test_zk: OK" << std::endl;
}
